export type Trip = {
  id: string;
  location: string;
  days: number;
  price: string;
  highlights: string[];
  imageURL: string;
};

export const popularTrips: Trip[] = [
  {
    id: "1",
    location: "Paris, France",
    days: 5,
    price: "1500",
    highlights: [
      "Eiffel Tower",
      "Louvre Museum",
      "Seine River Cruise",
      "Notre-Dame Cathedral",
    ],
    imageURL: "/parris-two.jpg",
  },
  {
    id: "2",
    location: "Bali, Indonesia",
    days: 7,
    price: "1200",
    highlights: [
      "Uluwatu Temple",
      "Tegallalang Rice Terrace",
      "Seminyak Beach",
      "Monkey Forest",
    ],
    imageURL: "/bali.jpg",
  },
  {
    id: "3",
    location: "Tokyo, Japan",
    days: 6,
    price: "1800",
    highlights: [
      "Shibuya Crossing",
      "Tokyo Skytree",
      "Meiji Shrine",
      "Tsukiji Fish Market",
    ],
    imageURL: "/tokyo.jpg",
  },
  {
    id: "4",
    location: "Rome, Italy",
    days: 4,
    price: "1100",
    highlights: ["Colosseum", "Vatican Museums", "Trevi Fountain", "Pantheon"],
    imageURL: "https://example.com/images/rome.jpg",
  },
  {
    id: "5",
    location: "Sydney, Australia",
    days: 7,
    price: "1900",
    highlights: [
      "Sydney Opera House",
      "Bondi Beach",
      "Harbour Bridge",
      "Royal Botanic Garden",
    ],
    imageURL: "https://example.com/images/sydney.jpg",
  },
  {
    id: "6",
    location: "Cape Town, South Africa",
    days: 5,
    price: "1400",
    highlights: [
      "Table Mountain",
      "Robben Island",
      "Cape Point",
      "Kirstenbosch Gardens",
    ],
    imageURL: "https://example.com/images/cape-town.jpg",
  },
  {
    id: "7",
    location: "New York City, USA",
    days: 3,
    price: "1300",
    highlights: [
      "Times Square",
      "Central Park",
      "Statue of Liberty",
      "Broadway",
    ],
    imageURL: "https://example.com/images/new-york.jpg",
  },
  {
    id: "8",
    location: "Bangkok, Thailand",
    days: 4,
    price: "1000",
    highlights: [
      "Grand Palace",
      "Wat Arun",
      "Chatuchak Market",
      "Floating Markets",
    ],
    imageURL: "https://example.com/images/bangkok.jpg",
  },
  {
    id: "9",
    location: "Istanbul, Turkey",
    days: 5,
    price: "1100",
    highlights: [
      "Hagia Sophia",
      "Blue Mosque",
      "Grand Bazaar",
      "Bosphorus Cruise",
    ],
    imageURL: "https://example.com/images/istanbul.jpg",
  },
  {
    id: "10",
    location: "Dubai, UAE",
    days: 4,
    price: "1600",
    highlights: [
      "Burj Khalifa",
      "Dubai Mall",
      "Palm Jumeirah",
      "Desert Safari",
    ],
    imageURL: "https://example.com/images/dubai.jpg",
  },
  {
    id: "11",
    location: "Santorini, Greece",
    days: 5,
    price: "1400",
    highlights: ["Oia Sunset", "Fira", "Red Beach", "Ancient Thera"],
    imageURL: "https://example.com/images/santorini.jpg",
  },
  {
    id: "12",
    location: "Cairo, Egypt",
    days: 5,
    price: "1200",
    highlights: [
      "Pyramids of Giza",
      "Egyptian Museum",
      "Khan El Khalili",
      "Nile Cruise",
    ],
    imageURL: "https://example.com/images/cairo.jpg",
  },
  {
    id: "13",
    location: "London, England",
    days: 4,
    price: "1500",
    highlights: [
      "Buckingham Palace",
      "London Eye",
      "Tower of London",
      "British Museum",
    ],
    imageURL: "https://example.com/images/london.jpg",
  },
  {
    id: "14",
    location: "Barcelona, Spain",
    days: 4,
    price: "1300",
    highlights: [
      "Sagrada Familia",
      "Park Güell",
      "Gothic Quarter",
      "La Rambla",
    ],
    imageURL: "https://example.com/images/barcelona.jpg",
  },
  {
    id: "15",
    location: "Reykjavik, Iceland",
    days: 5,
    price: "1800",
    highlights: [
      "Blue Lagoon",
      "Golden Circle",
      "Northern Lights",
      "Thingvellir National Park",
    ],
    imageURL: "https://example.com/images/reykjavik.jpg",
  },
  {
    id: "16",
    location: "Amsterdam, Netherlands",
    days: 3,
    price: "1200",
    highlights: [
      "Canal Cruise",
      "Rijksmuseum",
      "Anne Frank House",
      "Van Gogh Museum",
    ],
    imageURL: "https://example.com/images/amsterdam.jpg",
  },
  {
    id: "17",
    location: "Marrakech, Morocco",
    days: 4,
    price: "1000",
    highlights: [
      "Jemaa el-Fnaa",
      "Majorelle Garden",
      "Bahia Palace",
      "Atlas Mountains",
    ],
    imageURL: "https://example.com/images/marrakech.jpg",
  },
  {
    id: "18",
    location: "Lisbon, Portugal",
    days: 4,
    price: "1100",
    highlights: ["Belém Tower", "Alfama", "Jerónimos Monastery", "LX Factory"],
    imageURL: "https://example.com/images/lisbon.jpg",
  },
  {
    id: "19",
    location: "Kyoto, Japan",
    days: 3,
    price: "1400",
    highlights: [
      "Fushimi Inari Shrine",
      "Kinkaku-ji",
      "Arashiyama Bamboo Grove",
      "Gion District",
    ],
    imageURL: "https://example.com/images/kyoto.jpg",
  },
  {
    id: "20",
    location: "Phuket, Thailand",
    days: 5,
    price: "1300",
    highlights: [
      "Patong Beach",
      "Phi Phi Islands",
      "Big Buddha",
      "Old Phuket Town",
    ],
    imageURL: "https://example.com/images/phuket.jpg",
  },
];
